import Head from "next/head";
import Header from "./header";
import Footer from "./footer";
import { Paper } from "@mui/material";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>To-Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Paper>
        <main>{children}</main>
      </Paper>
      <Footer />
    </>
  );
}
